from atlanticus.data_producers.sql import (
    DataValueKind,
    SqlLoadStrategy,
    SqlSourceDefinition,
    SqlStorageMode,
)
from atlanticus.operational_data.processes.dispatch.catalog.columns import column

REFERENCE_DEDUPE_COLUMNS = ('shift_id',)

DEFINITION = SqlSourceDefinition(
    source_key='shift_info',
    source_table='common.ShiftInfo',
    enabled=False,
    storage_mode=SqlStorageMode.PARTITIONED,
    load_strategy=SqlLoadStrategy.SCOPED,
    scope_column='ShiftId',
    scope_output_column='shift_id',
    materialization_name='shift',
    partition_dimensions=('year', 'month', 'day', 'turn'),
    columns=(
        column(
            source_name='shiftindex',
            output_name='shiftindex',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftId',
            output_name='shift_id',
            value_kind=DataValueKind.INTEGER,
            required=True,
        ),
        column(
            source_name='ShiftName',
            output_name='shift_name',
            value_kind=DataValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='DbName',
            output_name='db_name',
            value_kind=DataValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='ShiftYear',
            output_name='shift_year',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftMonth',
            output_name='shift_month',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftDay',
            output_name='shift_day',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftSuffix',
            output_name='shift_suffix',
            value_kind=DataValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='FullShiftSuffix',
            output_name='full_shift_suffix',
            value_kind=DataValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='ShiftStartSecSinceMidnight',
            output_name='shift_start_sec_since_midnight',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftStartTimestamp',
            output_name='shift_start_timestamp',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftStartTimestampUtc',
            output_name='shift_start_timestamp_utc',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftStartDate',
            output_name='shift_start_date',
            value_kind=DataValueKind.DATETIME,
            required=False,
        ),
        column(
            source_name='ShiftStartDateTime',
            output_name='shift_start_date_time',
            value_kind=DataValueKind.DATETIME,
            required=False,
        ),
        column(
            source_name='FullShiftName',
            output_name='full_shift_name',
            value_kind=DataValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Holiday',
            output_name='holiday',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='Crew',
            output_name='crew',
            value_kind=DataValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='ShiftDuration',
            output_name='shift_duration',
            value_kind=DataValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='ShiftDate',
            output_name='shift_date',
            value_kind=DataValueKind.DATETIME,
            required=False,
        ),
    ),
)
