# Centraliza los identificadores Dash propios de las superficies operacional y de catálogo; el workflow genérico usa IDs del Manager.
# Este espejo conserva exactamente el mismo AST y comportamiento que producción.

from __future__ import annotations

_PREFIX = 'ada-operational-manager'

USER = f'{_PREFIX}-user'
AREA = f'{_PREFIX}-area'
POSITION = f'{_PREFIX}-position'
GROUP = f'{_PREFIX}-group'
ASSIGNMENT_REVISION = f'{_PREFIX}-assignment-revision'
ASSIGNMENT_SAVE = f'{_PREFIX}-assignment-save'
ASSIGNMENT_REPROJECT = f'{_PREFIX}-assignment-reproject'
ASSIGNMENT_RESULT = f'{_PREFIX}-assignment-result'
ASSIGN_FEEDBACK = f'{_PREFIX}-assign-feedback'
ASSIGN_SEARCH = f'{_PREFIX}-assign-search'
ASSIGN_SIZE = f'{_PREFIX}-assign-size'
ASSIGN_PAGE = f'{_PREFIX}-assign-page'
ASSIGN_CURRENT_PAGE = f'{_PREFIX}-assign-current-page'
ASSIGN_LIST = f'{_PREFIX}-assign-list'
ASSIGN_STATUS = f'{_PREFIX}-assign-status'
ASSIGN_PREVIOUS = f'{_PREFIX}-assign-prev'
ASSIGN_NEXT = f'{_PREFIX}-assign-next'
ASSIGN_JUMP = f'{_PREFIX}-assign-jump'
ASSIGN_EDIT = f'{_PREFIX}-assign-edit'
ASSIGN_MODAL = f'{_PREFIX}-assign-modal'
ASSIGN_MODAL_BACKDROP = f'{_PREFIX}-assign-backdrop'
ASSIGN_MODAL_CANCEL = f'{_PREFIX}-assign-cancel'
ASSIGN_MODAL_CLOSE = f'{_PREFIX}-assign-close'
ASSIGN_SELECTED_NAME = f'{_PREFIX}-assign-selected-name'
ASSIGN_MODAL_STATUS = f'{_PREFIX}-assign-modal-status'

CATALOG_EDITOR = f'{_PREFIX}-catalog-editor'
CATALOG_SAVE_DRAFT = f'{_PREFIX}-catalog-save-draft'
CATALOG_SAVE_RESULT = f'{_PREFIX}-catalog-save-result'
POSITION_SELECT = f'{_PREFIX}-position-select'
POSITION_ID = f'{_PREFIX}-position-id'
POSITION_LABEL = f'{_PREFIX}-position-label'
POSITION_ACTIVE = f'{_PREFIX}-position-active'
POSITION_APPLY = f'{_PREFIX}-position-apply'
POSITION_RESULT = f'{_PREFIX}-position-result'
POSITION_SEARCH = f'{_PREFIX}-position-search'
POSITION_SIZE = f'{_PREFIX}-position-size'
POSITION_PAGE = f'{_PREFIX}-position-page'
POSITION_CURRENT_PAGE = f'{_PREFIX}-position-current-page'
POSITION_LIST = f'{_PREFIX}-position-list'
POSITION_STATUS = f'{_PREFIX}-position-status'
POSITION_PREVIOUS = f'{_PREFIX}-position-prev'
POSITION_NEXT = f'{_PREFIX}-position-next'
POSITION_JUMP = f'{_PREFIX}-position-jump'
POSITION_EDIT = f'{_PREFIX}-position-edit'
POSITION_NEW = f'{_PREFIX}-position-new'
POSITION_MODAL = f'{_PREFIX}-position-modal'
POSITION_MODAL_BACKDROP = f'{_PREFIX}-position-backdrop'
POSITION_MODAL_CANCEL = f'{_PREFIX}-position-cancel'
POSITION_MODAL_CLOSE = f'{_PREFIX}-position-close'
